### ISSUE TITLE
Support the MangoPi MQ-Pro

### ISSUE THREAD

**Issue by IsaacWoods** [IsaacWoods/poplar#100]
### Getting the kernel running

- [ ] Get OpenSBI and Seed booting via FEL (#99)
- [ ] Support loading files in Seed from a ramdisk loaded into memory with FEL
- [ ] Support the `Sv39` paging model (as this is all the D1 supports :()
- [ ] Generalise `seed_riscv`'s ELF loading to any source of files
- [ ] Successfully boot into the kernel!

### Boot from persistent media

- [ ] Work out how to update SD cards without just writing a whole new disk image to them (or do we care?)
- [ ] Get a test `boot0` running from SRAM that can output to the UART running from the SD card
- [ ] Initialize the DRAM in our `boot0`
- [ ] Load OpenSBI and Seed from the SD card in `boot0`
- [ ] Successfully run OpenSBI + Seed
- [ ] Write SDHC driver for Seed
- [ ] Load kernel from SD card and boot into it!
- [ ] Work out how to fit the weird headers etc. into a nice GPT scheme

**Comment by IsaacWoods** [comment]
Adding a note here to hopefully remember (we're not going to be near our workstation for a while :( ). I think we need to do a VMA fence after switching to new sets of page tables - I don't think this is going to be what's causing issues on the D1, but is the correct thing to do.

**Comment by IsaacWoods** [comment]
Also some thoughts about debugging on real hardware - I wonder if we could get some kind of timer running in M-mode (with an altered OpenSBI I guess) that pings back a set of registers / other info over UART. This would be a useful extra tool for dealing with stuff like the core seemingly freezing when entering usermode (although we need to have a look at our trap handling to rule out dumb mistakes first).

Could also look at the `ebreak` instruction to see if we can do any instrumentation through that via M-mode too.
