### ISSUE TITLE
USB support - EHCI

### ISSUE THREAD

**Issue by IsaacWoods** [IsaacWoods/poplar#101]
- [x] Enumerate EHCI controllers with new userspace bus driver
- [x] Initialize controller
- [x] Enumerate and reset connected ports
- [x] Send control transfers
- [x] Get device descriptors from connected devices

### Spin-off tasks
- [x] Disassociate Memory Objects from virtual addresses (mappings will instead happen via the Address Space)
- [x] Abstract out userspace `MemoryObject` and `MappedMemoryObject` representations (cc #71)
- [x] Provide managed (i.e. has an allocator) physically-mapped memory region thing
