### ISSUE TITLE
Road to Poplar v0.1

### ISSUE THREAD

**Issue by IsaacWoods** [IsaacWoods/poplar#114]
## Tasks
- [ ] Move D1 bringup experimentation to branch + PR
- [ ] Polish and publish `picotoml`
- [ ] Remove image capabilities in current form
- [ ] Get `x86_64` port booting to userspace again + running shell with USB keyboard etc.
- [ ] Specify overall Poplar version in `Poplar.toml` and pass through to kernel somehow
- [ ] Describe resources passed to userspace (e.g. framebuffer, PCI info, version info, etc.) with generalised Ptah representation + one syscall
- [ ] (?) Split `poplar` library into bit shared by kernel and userspace utilities (maybe move later into our custom `std`)
- [ ] Move EHCI driver over to drive transactions by interrupt + use futures to avoid transactions stalling to completion
- [ ] Support USB mice in HID layer + render cursor
- [ ] Add support for methods to Ginkgo
- [ ] Add `version` shell function to get Poplar version, platform, build information etc.
- [ ] Add builtin list type to Ginkgo
- [ ] Add shell function to list PlatformBus devices
- [ ] Add better error handling to Ginkgo so it doesn't hang the shell on parsing / interpreter errors lmao
